export const products = [
  {
    id: 1,
    image: "/assets/forok.png",
    name: "Indian Sharee",
    price: 1700,
    reviews: 162,
    rating: 3,
    discount: 20,
  },
  {
    id: 2,
    image: "/assets/shirt.png",
    name: "Half Sleeve Shirt",
    price: 2100,
    reviews: 65,
    rating: 3,
    discount: 40,
  },
  {
    id: 3,
    image: "/assets/sharee.png",
    name: "Woman waring Sharie",
    price: 3900,
    reviews: 90,
    rating: 3,
    discount: 15,
  },
  {
    id: 4,
    image: "/assets/half-shirt.png",
    name: "Checkered Shirt",
    price: 2500,
    reviews: 150,
    rating: 3,
    discount: 12,
  },
  {
    id: 5,
    image: "/assets/forok.png",
    name: "Indian Sharee",
    price: 1700,
    reviews: 162,
    rating: 3,
    discount: 20,
  },
  {
    id: 6,
    image: "/assets/shirt.png",
    name: "Half Sleeve Shirt",
    price: 2100,
    reviews: 65,
    rating: 3,
    discount: 40,
  },
  {
    id: 7,
    image: "/assets/sharee.png",
    name: "Woman waring Sharie",
    price: 3900,
    reviews: 90,
    rating: 3,
    discount: 15,
  },
  {
    id: 8,
    image: "/assets/half-shirt.png",
    name: "Checkered Shirt",
    price: 2500,
    reviews: 150,
    rating: 3,
    discount: 12,
  },
];

export const newArrivals = [
  {
    id: 1,
    image: "/assets/indian-sharee.png",
    name: "Indian Sharee",
    price: 3500,
  },
  {
    id: 2,
    image: "/assets/hoodie.jpg",
    name: "Hoodie",
    price: 1200,
  },
  {
    id: 3,
    image: "/assets/plazu.png",
    name: "Plazu",
    price: 2300,
  },
  {
    id: 4,
    image: "/assets/jacket.png",
    name: "Jacket",
    price: 1800,
  },
  {
    id: 5,
    image: "/assets/indian-sharee.png",
    name: "Indian Sharee",
    price: 3500,
  },
  {
    id: 6,
    image: "/assets/hoodie.jpg",
    name: "Hoodie",
    price: 1200,
  },
];
